DROP TABLE IF EXISTS POINTS;
DROP TABLE IF EXISTS PIPELINESYSTEM;

CREATE TABLE POINTS(
IDA VARCHAR,
IDB VARCHAR);

CREATE TABLE PIPELINESYSTEM(
IDX VARCHAR,
IDY VARCHAR,
LENGTH INT);

INSERT INTO pipelinesystem
VALUES ('1', '2', 10);
INSERT INTO pipelinesystem
VALUES ('2', '3', 20);
INSERT INTO pipelinesystem
VALUES ('3', '4', 30);
INSERT INTO pipelinesystem
VALUES ('3', '5', 15);
INSERT INTO pipelinesystem
VALUES ('6', '7', 20);

INSERT INTO points VALUES ('2', '5');
INSERT INTO points VALUES ('2', '6');
INSERT INTO points VALUES ('6', '7');